title: "My RF + Space Blog"
description: "Tracking my journey through electromagnetics, RF design, antennas, and satellite comm before UT Austin."
remote_theme: mmistakes/minimal-mistakes


# Author info
author:
  name: "Sahithya Kattamuri"
  avatar: /RF_blog/assets/images/profile_pic.png
  bio: "EM/RF enthusiast | MS ECE @ UT Austin (Fall '25)"
  location: "USA"



# Site base URL and repository
url: "https://Sahithya2003.github.io"
baseurl: "/RF_blog"
repository: "Sahithya2003/RF_blog"

# Plugins required for Minimal Mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-include-cache
  - jekyll-paginate

# Pagination settings
paginate: 5
paginate_path: /page:num/

# Markdown + Math support
markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax
  syntax_highlighter: rouge

# Posts settings
collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      toc: true
