title: "My RF + Space Journey"
description: "A blog tracking my prep in applied electromagnetics, RF design, and satellite communication before UT Austin."
theme: minima
author: Sahithya Kattamuri
baseurl: ""
url: "https://Sahithya2003.github.io/RF_blog"
